from abc import ABC, abstractmethod

class Logger(ABC):
    @abstractmethod
    def info(self, message: str, **kwargs): ...
    @abstractmethod
    def warning(self, message: str, **kwargs): ...
    @abstractmethod
    def error(self, message: str, **kwargs): ...
    @abstractmethod
    def debug(self, message: str, **kwargs): ...
